FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1

ARG DJANGO_DEBUG

ENV DJANGO_DEBUG=${DJANGO_DEBUG}

ENV POSTGRES_HOST=host.docker.internal
ENV POSTGRES_PORT=5432
ENV POSTGRES_DB=ctibutler_database
ENV POSTGRES_USER=ctibutler
ENV ARANGODB_HOST_URL=http://host.docker.internal:8529
ENV ARANGODB_USERNAME=ctibutler
ENV MAX_PAGE_SIZE=50
ENV DEFAULT_PAGE_SIZE=50
ENV ATLAS_BUCKET_ROOT_PATH=https://downloads.ctibutler.com/mitre-atlas-repo-data/
ENV CTI_BUTLER_ROOT=https://downloads.ctibutler.com/
ENV LOCATION_BUCKET_ROOT_PATH=https://downloads.ctibutler.com/location2stix-manual-output/
ENV SECTOR_BUCKET_ROOT_PATH=https://downloads.ctibutler.com/sector2stix-manual-output/
ENV CWE_BUCKET_ROOT_PATH=https://downloads.ctibutler.com/cwe2stix-manual-output/
ENV CAPEC_BUCKET_ROOT_PATH=https://downloads.ctibutler.com/mitre-capec-repo-data/
ENV ATTACK_ENTERPRISE_BUCKET_ROOT_PATH=https://downloads.ctibutler.com/mitre-attack-enterprise-repo-data/
ENV ATTACK_MOBILE_BUCKET_ROOT_PATH=https://downloads.ctibutler.com/mitre-attack-mobile-repo-data/
ENV ATTACK_ICS_BUCKET_ROOT_PATH=https://downloads.ctibutler.com/mitre-attack-ics-repo-data/
ENV DISARM_BUCKET_ROOT_PATH=https://downloads.ctibutler.com/disarm2stix-manual-output/
ENV D3FEND_BUCKET_ROOT_PATH=https://downloads.ctibutler.com/d3fend2stix-manual-output/
ENV DJANGO_SETTINGS_MODULE=ctibutler.settings
ENV CELERY_BROKER_URL=redis://host.docker.internal:6379/0
ENV result_backend=redis://host.docker.internal:6379/0

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN --mount=type=cache,target=/root/.cache \
    pip install -r requirements.txt

COPY . /usr/src/app

RUN python utilities/download_tie_models.py