# Generated by Django 5.2.9 on 2026-02-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('attack-update', 'Attack Update'), ('cwe-update', 'Cwe Update'), ('capec-update', 'Capec Update'), ('arango-cti-processor', 'Cti Processor'), ('atlas-update', 'Atlas Update'), ('location-update', 'Location Update'), ('disarm-update', 'Disarm Update'), ('sector-update', 'Sector Update'), ('d3fend-update', 'D3Fend Update')], max_length=64),
        ),
    ]
